spring:
    artemis:
        host: ${ACTIVEMQ_ARTEMIS_HOST:localhost}
        port: ${ACTIVEMQ_ARTEMIS_PORT:61616}
        user: admin
        password: admin
    kafka:
        bootstrap-servers: localhost:${KAFKA_PORT:9093}
