spring:
    application:
        name: Analytics-Service
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: '@spring.profiles.active@'
    kafka:
        bootstrap-servers: localhost:9092

spring.cloud.stream:
    function:
        definition: getUri;upperCase # | or , doesn't work
    bindings:
        getUri-in-0:
            destination: page-view
        getUri-out-0:
            destination: page-uri
        upperCase-in-0:
            destination: page-uri
        upperCase-out-0:
            destination: page-uri-upper
    kafka.streams.binder.functions:
        getUri.applicationId: getUri
        upperCase.applicationId: upperCase
    kafka.bindings:
        getUri-in-0:
            consumer:
                configuration:
                    value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        getUri-out-0:
            producer:
                configuration:
                    value.serializer: org.apache.kafka.common.serialization.StringSerializer
        upperCase-in-0:
            consumer:
                configuration:
                    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        upperCase-out-0:
            producer:
                configuration:
                    value.serializer: org.apache.kafka.common.serialization.StringSerializer


server:
    port: 8084
logging:
    level:
        'org.apache.kafka': info




